Port to Python 3
sugarlabs/turtlepond pull request #8
Opened 2019-12-07 14:19 UTC by Bottersnike

Tested within `sugar-activity3`. When testing within a local sugar environment, I encountered a DBus error where it was attempting to cast the repr of a DBus into an int. I believe this to be an issue with my local sugar environment and not with this activity, however this needs tested by someone with a confirmed-working local sugar environment.

2019-12-07 14:42 UTC, tchx84 requested changes
Just a silly typo.

2019-12-07 14:42 UTC, tchx84 commented on genxo.py
> +#!/usr/bin/env python5
Python 5?

2019-12-07 14:49 UTC, tchx84 commented
Other comments fro our IRC chat:

* the color of the turtle seems changed, but it might be an earlier regression, extra kudos if you fix it ;)
* make sure to double check with some of the examples from https://help.sugarlabs.org/en/turtle_in_a_pond.html to import custom strategies

Thanks! this is awesome.

2019-12-07 15:02 UTC, Bottersnike commented
All builtin strategies appear to work, and all strategies on the wiki appear to be functioning python 3 code. I'm unable to test importing from the journal as my local sugar instance refuses to start turtlepond (due to unrelated issues) however manually loaded a number of custom strategies by editing the source and none failed to work

2019-12-07 15:18 UTC, Bottersnike commented on genxo.py
> +#!/usr/bin/env python5
Fixed by the below squashed push

2019-12-08 20:29 UTC, quozl commented
Thanks.  Reviewed.  Tested starting from Sugar.

2019-12-08 20:30 UTC, merged